name: smiling_celeba_non_dp_98i_female #change this in accordance with the attributes lower down
test_batch_size: 128 #128 #TODO should this be lower? 134 of are 
batch_size: 32 #256
num_microbatches: 32 #256
lr: 0.00005
momentum: 0.9
decay: 5e-4
S: 5
z: 1.5
mu: 0.9
dp: True #False
epochs: 3 #Kinda more like one?
save_on_epochs: [10, 20, 40, 60]
optimizer: Adam
scheduler: False

save_model: True
dataset: celeba
model: PretrainedRes

image_dir: /workspace/celeba/img_align_celeba/img_align_celeba/
#for colab /content/celeba/img_align_celeba/img_align_celeba/
#for vast.ai
attr_path: /workspace/celeba/imbalanced_attr/0.9.csv
#for colab /content/celeba/imbalanced_attr/0.9.csv
#for vast.I
selected_attr: Smiling
protected_attr: Male
labels: [0, 1]
multi_gpu: True #Make sure to update this for remote machines

#U = unique to this configuration
