name: smiling_celeba_non_dp_27k_female #change this in accordance with the attributes lower down
test_batch_size: 128 #128
batch_size: 128 #256
num_microbatches: 128 #256
lr: 0.00005
momentum: 0.9
decay: 5e-4
S: 5
z: 0.5
mu: 0.9
dp: True #False
epochs: 10
save_on_epochs: [10, 20, 40, 60]
optimizer: Adam
scheduler: False

save_model: True
dataset: celeba
model: resnet

image_dir: /Users/nvw3/Downloads/celeba/img_align_celeba/img_align_celeba/ #Changed for local env on MacBook soemtimes need double folder structure as comes out of the zip
#/workspace/celeba/img_align_celeba/img_align_celeba/ for on jupyter
attr_path: /Users/nvw3/Downloads/celeba/imbalanced_attr/27k_female.csv #Changed for local env on MacBook
#/workspace/celeba/img_align_celeba/img_align_celeba/ for on jupyter
selected_attr: Smiling
protected_attr: Male
labels: [0, 1]
multi_gpu: False #Make sure to update this for remote machines

