test_batch_size: 25 #25
batch_size: 32 #32
num_microbatches: 16 #16
lr: 0.0001 #0.0001
momentum: 0.9
decay: 5e-4
S: 5
z: 0.5
dp: True #True
epochs: 6 #60
save_on_epochs: [1,2,3] #[5, 10, 50]
optimizer: Adam

mu: 0.9
ds_size: 600 #60000

key_to_drop: 5 #5
number_of_entries: 500 #500
number_of_entries_test: 1000 #1000
inat_drop_proportional: True

save_model: True
dataset: celeba
model: inception
densenet_depth: 100 #100
scheduler: True
