# -*- coding: utf-8 -*-
"""startup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iz9cYKfgciZac3d6m7B6fAB0VmK6r3PD
"""

!nvidia-smi
!lscpu

!apt-get update ; apt-get -y install curl ; apt install unzip -qq ; apt-get install git -q ; pip install absl-py ; pip install matplotlib ; pip install scipy ; pip install tensorboardX ; pip install sklearn ; pip install wandb ; pip install tensorboard ; pip install gsutil

#Replace this with your own Wandb login
!wandb login 3901faa3f69c0e6b1eaf7d3c49f7dbb8e3886dec

#Install google cloud sdk
#!curl https://sdk.cloud.google.com | bash

!rm celeba.zip
#Get Dataset from google cloud bucket
!gsutil cp gs://celeba_1/celeba.zip celeba.zip

!rm -rf __MACOSX/
!rm -rf celeba/
!unzip -qq celeba.zip

#Get code from repository
!rm -rf deep-learning-fairness-light/
!git clone https://github.com/nvw1/deep-learning-fairness-light.git

#Running the main file"
!cd deep-learning-fairness-light ; python fairness.py --name no90 #Could adc "resumed_model" here